# -*- coding: utf-8 -*-
"""Adapter_Pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LrEMGX_RwPccwLMkS9dkdfE9fRK3NXNH
"""

from abc import ABC, abstractmethod

# Legacy Printer / Adaptee / Legacy Code
class LegacyPrinter:
  def print_document(self):
    print("Legacy printer printing document")

# Target / Our Code Using This Interface(class)
class Printer(ABC):
  @abstractmethod
  def print_new_document(self):
    pass

# Adapter (implementing Printer class)
class Adapter(Printer):
  def __init__(self):
    self._legacyPrinter = LegacyPrinter()

  def print_new_document(self):
    self._legacyPrinter.print_document()

def client_code(printer):
    printer.print_new_document()

if __name__ == '__main__':
    # Using the Adapter
    adapter = Adapter()
    client_code(adapter)