# -*- coding: utf-8 -*-
"""Bridge_Pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6qhZrrbZAkV4Wq7C2Qp7RAqAOizVhXQ
"""

from typing import Mapping
from abc import ABC, abstractmethod

class Engine(ABC):
  @abstractmethod
  def start(self):
    pass

class PetrolEngine(Engine):
  def start(self):
    print("Petrol engine strating right now...")

class DieselEngine(Engine):
  def start(self):
    print("Diesel engine strating with huge noise...")

class HybridEngine(Engine):
  def start(self):
    print("Hybrid engine strating with no noise...")

class Car(ABC):
  def __init__(self, engine: Engine):
    self._engine = engine

  @abstractmethod
  def drive(self):
    pass

class SedanCar(Car):
  def drive(self):
    self._engine.start()
    print("Sedan car driving at 100kmph...")

class SUVCar(Car):
  def drive(self):
    self._engine.start()
    print("SUV car driving at 75kmph...")

def main():
    # Create engines
    petrol_engine = PetrolEngine()
    diesel_engine = DieselEngine()
    hybrid_engine = HybridEngine()

    # Create cars with different engines
    sedan_with_petrol = SedanCar(petrol_engine)
    suv_with_diesel = SUVCar(diesel_engine)
    sedan_with_hybrid = SedanCar(hybrid_engine)
    suv_with_petrol = SUVCar(petrol_engine)

    # Drive cars
    print("---- Sedan with Petrol Engine ----")
    sedan_with_petrol.drive()

    print("\n---- SUV with Diesel Engine ----")
    suv_with_diesel.drive()

    print("\n---- Sedan with Hybrid Engine ----")
    sedan_with_hybrid.drive()

    print("\n---- SUV with Petrol Engine ----")
    suv_with_petrol.drive()

if __name__ == "__main__":
    main()