# -*- coding: utf-8 -*-
"""Composite_Pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RVFs_25ML-HhV0Atme1zPIEG2wMQ2mmO
"""

from abc import ABC, abstractmethod

class FileSystemItem(ABC):
  @abstractmethod
  def ls(self):
    pass

  @abstractmethod
  def openAll(self):
    pass

  @abstractmethod
  def getSize(self) -> int:
    pass

  @abstractmethod
  def getName(self) -> str:
    pass

  @abstractmethod
  def isFolder(self) -> bool:
    pass

  @abstractmethod
  def cd(self, name: str) -> "FileSystemItem | None":
    pass

class File(FileSystemItem):
  def __init__(self, name, size):
    self.name = name
    self.size = size

  def ls(self):
    print(self.getName())

  def openAll(self):
    print(self.getName())

  def getSize(self):
    return self.size

  def cd(self, name):
    return None

  def getName(self):
    return self.name

  def isFolder(self):
    return False

class Folder(FileSystemItem):
  def __init__(self, name):
    self.name = name
    self.items = []

  def addItem(self, item: FileSystemItem):
    self.items.append(item)

  def ls(self):
    for item in self.items:
      print(item.getName())

  def openAll(self):
    print(self.getName())
    for item in self.items:
      item.openAll()

  def cd(self, name):
    for item in self.items:
      if item.getName() == name:
        return item
    return None

  def getSize(self):
    total = 0
    for item in self.items:
      total += item.getSize()
    return total

  def getName(self):
    return self.name

  def isFolder(self):
    return True

def main():
    # Create files
    file1 = File("file1.txt", 100)
    file2 = File("file2.txt", 200)
    file3 = File("file3.log", 300)

    # Create folders
    root = Folder("root")
    documents = Folder("documents")
    logs = Folder("logs")

    # Build folder structure
    documents.addItem(file1)
    documents.addItem(file2)

    logs.addItem(file3)

    root.addItem(documents)
    root.addItem(logs)

    # ---- Test ls() ----
    print("=== ls on root ===")
    root.ls()

    print("\n=== ls on documents ===")
    documents.ls()

    # ---- Test openAll() ----
    print("\n=== openAll on root ===")
    root.openAll()

    # ---- Test getSize() ----
    print("\n=== Size calculations ===")
    print("documents size:", documents.getSize())
    print("logs size:", logs.getSize())
    print("root size:", root.getSize())

    # ---- Test cd() ----
    print("\n=== cd operations ===")
    item = root.cd("documents")
    if item:
        print("cd into documents successful:", item.getName())

    sub_item = item.cd("file1.txt")
    if sub_item:
        print("Found file:", sub_item.getName())
    else:
        print("Cannot cd into file1.txt")

    invalid = root.cd("non_existing")
    print("cd into non_existing:", invalid)


if __name__ == "__main__":
    main()