# -*- coding: utf-8 -*-
"""Factory_Pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UW6ewzkFubIFoRN7lXR0MLUvcG7ETdPn
"""

# Without Factory Pattern

from abc import ABC, abstractmethod

class Pizza(ABC):
  @abstractmethod
  def createPizza(self):
    pass

class CheesePizza(Pizza):
  def createPizza(self):
    print("Cheese Pizza Created!")

class VegetablePizza(Pizza):
  def createPizza(self):
    print("Vegetable Pizza Created!")

def main():
  mytype = 1
  if mytype == 1:
    pizza = CheesePizza()
  else:
    pizza = VegetablePizza()
  pizza.createPizza()

  mytype = 2
  if mytype == 1:
    pizza = CheesePizza()
  else:
    pizza = VegetablePizza()
  pizza.createPizza()

if __name__ == "__main__":
  main()

# Simple Factory Pattern

from abc import ABC, abstractmethod

class Pizza(ABC):
  @abstractmethod
  def createPizza(self):
    pass

class CheesePizza(Pizza):
  def createPizza(self):
    print("Cheese Pizza Created!")

class VegetablePizza(Pizza):
  def createPizza(self):
    print("Vegetable Pizza Created!")


class PizzaFactory():
  @staticmethod
  def getPizza(type: int) -> Pizza:
    if(type == 1):
      return CheesePizza()
    else:
      return VegetablePizza()

def main():
  pizza = PizzaFactory.getPizza(1)
  pizza.createPizza()

  pizza = PizzaFactory.getPizza(2)
  pizza.createPizza()


if __name__=="__main__":
  main()

from abc import ABC, abstractmethod

# Product
class Pizza(ABC):
    @abstractmethod
    def createPizza(self):
        pass

# Concrete Products
class HutCheesePizza(Pizza):
    def createPizza(self):
        print("Hut Cheese Pizza Created!")

class HutVegetablePizza(Pizza):
    def createPizza(self):
        print("Hut Vegetable Pizza Created!")

class KingCheesePizza(Pizza):
    def createPizza(self):
        print("King Cheese Pizza Created!")

class KingVegetablePizza(Pizza):
    def createPizza(self):
        print("King Vegetable Pizza Created!")

# Abstract Factory
class Factory(ABC):
    @abstractmethod
    def getPizza(self, type: int) -> Pizza:
        pass

# Concrete Factories
class PizzaHut(Factory):
    def getPizza(self, type: int) -> Pizza:
        if type == 1:
            return HutCheesePizza()
        else:
            return HutVegetablePizza()

class KingPizza(Factory):
    def getPizza(self, type: int) -> Pizza:
        if type == 1:
            return KingCheesePizza()
        else:
            return KingVegetablePizza()

# Client
def main():
    factory1 = PizzaHut()
    pizza1 = factory1.getPizza(1)
    pizza1.createPizza()

    factory2 = KingPizza()
    pizza2 = factory2.getPizza(2)
    pizza2.createPizza()

if __name__ == "__main__":
    main()

# Abstract Factory Pattern

from abc import ABC, abstractmethod

class Pizza(ABC):
  @abstractmethod
  def createPizza(self):
    pass

class HutCheesePizza(Pizza):
  def createPizza(self):
    print("Hut Cheese Pizza Created!")

class HutVegetablePizza(Pizza):
  def createPizza(self):
    print("Hut Vegetable Pizza Created!")

class KingCheesePizza(Pizza):
  def createPizza(self):
    print("King Cheese Pizza Created!")

class KingVegetablePizza(Pizza):
  def createPizza(self):
    print("King Vegetable Pizza Created!")

class Burger(ABC):
  @abstractmethod
  def createBurger(self):
    pass

class HutCheeseBurger(Burger):
  def createBurger(self):
    print("Hut Cheese Burger Created!")

class HutVegetableBurger(Burger):
  def createBurger(self):
    print("Hut Vegetable Burger Created!")

class KingCheeseBurger(Burger):
  def createBurger(self):
    print("King Cheese Burger Created!")

class KingVegetableBurger(Burger):
  def createBurger(self):
    print("King Vegetable Burger Created!")


class Factory(ABC):
  @abstractmethod
  def getPizza(self, type: int) -> Pizza:
    pass
  @abstractmethod
  def getBurger(self, type: int) -> Burger:
    pass

class PizzaHut(Factory):
  def getPizza(self, type: int) -> Pizza:
    if(type == 1):
      return HutCheesePizza()
    else:
      return HutVegetablePizza()

  def getBurger(self, type: int) -> Burger:
    if(type == 1):
      return HutCheeseBurger()
    else:
      return HutVegetableBurger()

class KingPizza(Factory):
  def getPizza(self, type: int) -> Pizza:
    if(type == 1):
      return KingCheesePizza()
    else:
      return KingVegetablePizza()

  def getBurger(self, type: int) -> Burger:
    if(type == 1):
      return KingCheeseBurger()
    else:
      return KingVegetableBurger()


def main():
    # PizzaHut
    factory = PizzaHut()
    pizza = factory.getPizza(1)
    pizza.createPizza()
    burger = factory.getBurger(2)
    burger.createBurger()

    # KingPizza
    factory = KingPizza()
    pizza = factory.getPizza(2)
    pizza.createPizza()
    burger = factory.getBurger(1)
    burger.createBurger()


if __name__=="__main__":
  main()