# -*- coding: utf-8 -*-
"""Strategy_Pattern.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UP9sShBuM9QqhIraeEfOY9pwC3bGbO7S
"""

from abc import ABC, abstractmethod

class Walkable(ABC):
  @abstractmethod
  def walk(self):
    pass

class Talkable(ABC):
  @abstractmethod
  def talk(self):
    pass

class Flyable(ABC):
  @abstractmethod
  def fly(self):
    pass

class NormalWalk(Walkable):
  def walk(self):
    print("Robot walking normally...")

class SpecialWalk(Walkable):
  def walk(self):
    print("Robot walking specially...")

class NormalTalk(Talkable):
  def talk(self):
    print("Robot talking normally...")

class SpecialTalk(Talkable):
  def talk(self):
    print("Robot talking specially...")

class NormalFly(Flyable):
  def fly(self):
    print("Robot flying normally...")

class SpecialFly(Flyable):
  def fly(self):
    print("Robot flying specially...")

class Robot(ABC):
  def __init__(self, walk: Walkable, talk: Talkable, fly: Flyable):
    self.walk_strategy = walk
    self.talk_strategy = talk
    self.fly_strategy = fly

  @abstractmethod
  def project(self):
    pass

  def talk(self):
    self.talk_strategy.talk()

  def walk(self):
    self.walk_strategy.walk()

  def fly(self):
    self.fly_strategy.fly()

class ServiceRobot(Robot):
    def project(self):
        print("Service robot executing project...")

def main():
    robot1 = ServiceRobot(
        walk=NormalWalk(),
        talk=SpecialTalk(),
        fly=NormalFly()
    )

    robot1.project()
    robot1.walk()
    robot1.talk()
    robot1.fly()

    print("\n--- Changing behavior at runtime ---")

    robot1.w = SpecialWalk()
    robot1.f = SpecialFly()

    robot1.walk()
    robot1.fly()


if __name__ == "__main__":
    main()